## Assignment Day 3 Solution

## Q. Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [3]:
import numpy as np
array=np.arange(2,51,3)
print("Array of all the even integers from 2 to 50 with a stepsize of 3")
print(array)

Array of all the even integers from 2 to 50 with a stepsize of 3
[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


## Q. Accept two lists of 5 elements each from the user.Convert them to numpy arrays.Concatenate these arrays and print it. Also sort these arrays and print it.

In [14]:
import numpy as np 
a = np.array([1, 4, 5, 6, 5]) 
arr1 = np.sort(a)         
print(arr1)         

a = np.array([3, 5, 7, 2, 5]) 
arr2 = np.sort(a)         
print(arr2) 
    
a = np.array([[1, 4, 5, 6, 5], [3, 5, 7, 2, 5]]) 
arr1 = np.sort(a, axis = None)         
print (arr1)

[1 4 5 5 6]
[2 3 5 5 7]
[1 2 3 4 5 5 5 5 6 7]


## Q.Write a code snippet to find the dimensions of a ndarray and its size.

In [21]:
import numpy as np

# 2d array to list
arr = np.array([[1, 2, 3], [4, 5, 6], [3, 5, 7]])

print(f'{arr}')

list1 = arr.tolist()

print(f'{list1}')

[[1 2 3]
 [4 5 6]
 [3 5 7]]
[[1, 2, 3], [4, 5, 6], [3, 5, 7]]


## Q. How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
## Hint: np.newaxis, np.expand_dims

In [22]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

## Q. Consider two square numpy arrays. Stack them vertically and horizontally.
## Hint: Use vstack(), hstack()

In [23]:
import numpy as np
dt1 = np.array([1,2,3])
dt2 = np.array([4,5,6])

print(np.vstack((dt1, dt2)))

[[1 2 3]
 [4 5 6]]


## Q. How to get unique items and counts of unique items?

In [27]:
numbers = [1, 2, 2, 3, 9, 3, 4, 5, 9]
def get_unique_numbers(numbers):
    unique = []

    for number in numbers:
        if number in unique:
            continue
        else:
            unique.append(number)
    return unique


print(get_unique_numbers(numbers))

[1, 2, 3, 9, 4, 5]
